"""
point.builders.paths
~~~~~~~~~~~~~~~~~~~~

Learning path generation system.

Responsibilities
----------------

Generate learning path resources from
Point educational content.

Features
--------

- path extraction
- path validation
- markdown generation
- json generation

Pipeline
--------

Lessons
    ↓

Parser
    ↓

AST
    ↓

PathBuilder
    ↓

paths.json
paths/index.md

Overview
--------

Learning paths provide structured learning
journeys for students.

Example
-------

@path Backend Fundamentals

HTTP
REST
Authentication
Caching

@end

Produces:

Backend Fundamentals
    ↓
HTTP
    ↓
REST
    ↓
Authentication
    ↓
Caching
"""

from __future__ import annotations

import json
from dataclasses import (
    asdict,
    dataclass,
)
from pathlib import Path

from point.ast.nodes import (
    Lesson,
)
from point.ast.nodes import (
    Path as PathNode,
)


@dataclass(slots=True)
class LearningPath:
    """
    Learning path definition.

    Attributes
    ----------

    title:
        Learning path name.

    lessons:
        Ordered lesson sequence.
    """

    title: str

    lessons: list[str]


class PathBuilder:
    """
    Build learning path resources.

    Outputs
    -------

    paths.json

    paths/index.md
    """

    def build(
        self,
        lessons: list[Lesson],
        output_dir: Path,
    ) -> None:
        """
        Build learning path resources.

        Parameters
        ----------
        lessons:
            Parsed lesson ASTs.

        output_dir:
            Path output directory.
        """

        paths = self.extract_paths(lessons)

        output_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        self.write_json(
            paths,
            output_dir / "paths.json",
        )

        self.write_markdown(
            paths,
            output_dir / "index.md",
        )

    def extract_paths(
        self,
        lessons: list[Lesson],
    ) -> list[LearningPath]:
        """
        Extract learning paths from lessons.

        Parameters
        ----------
        lessons:
            Parsed lesson ASTs.

        Returns
        -------
        list[LearningPath]
        """

        paths: list[LearningPath] = []

        seen: set[str] = set()

        for lesson in lessons:
            for node in lesson.children:
                if not isinstance(
                    node,
                    PathNode,
                ):
                    continue

                if node.title in seen:
                    continue

                seen.add(node.title)

                paths.append(
                    LearningPath(
                        title=node.title,
                        lessons=node.lessons,
                    )
                )

        if not paths:
            paths.append(
                LearningPath(
                    title="Recommended Learning Order",
                    lessons=[lesson.title for lesson in lessons],
                )
            )

        paths.sort(key=lambda path: path.title.lower())

        return paths

    def write_json(
        self,
        paths: list[LearningPath],
        output_file: Path,
    ) -> None:
        """
        Write learning paths JSON.

        Parameters
        ----------
        paths:
            Learning paths.

        output_file:
            JSON output path.
        """

        data = [asdict(path) for path in paths]

        output_file.write_text(
            json.dumps(
                data,
                indent=4,
            ),
            encoding="utf-8",
        )

    def write_markdown(
        self,
        paths: list[LearningPath],
        output_file: Path,
    ) -> None:
        """
        Write learning paths markdown page.

        Parameters
        ----------
        paths:
            Learning paths.

        output_file:
            Markdown output path.
        """

        lines = [
            "# Learning Paths",
            "",
            "Structured learning journeys generated by Point.",
            "",
        ]

        for path in paths:
            lines.extend(
                [
                    f"## {path.title}",
                    "",
                ]
            )

            for index, lesson in enumerate(
                path.lessons,
                start=1,
            ):
                lines.append(f"{index}. {lesson}")

            lines.append("")

        output_file.write_text(
            "\n".join(lines),
            encoding="utf-8",
        )
